const clubs = [
    {
        id: "1",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/hacking.png",
        name: "0x1337: The Hacking Club",
        mail: "hacking.club@students.iiit.ac.in",
        website: "",
        category: "TECHNICAL",
        tagline: "Exploiting vulnerabilities for fun and profit",
        description:
            '[{"type":"paragraph","children":[{"text":"We are a club based on ethical hacking, where we try to familiarize people with different tools and ways of ethical hacking and make them aware about how cybersecurity is so important in today’s world."}]}]',
        instagram: "https://www.instagram.com/0x1337iiith/",
        facebook: "https://www.facebook.com/groups/hackingclubiiith",
        youtube: "https://www.youtube.com/channel/UCh8mysep91D52uOW47jN91A",
        twitter: "https://mobile.twitter.com/0x1337iiith",
        linkedin: "",
        discord: "https://discord.gg/xhDnu6Rnfh",
        __typename: "ClubType",
    },
    {
        id: "30",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/alumni.png",
        name: "Alumni Cell",
        mail: "alumnicell@iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "9",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/asec_color.jpg",
        name: "Amateur Sports Enthusiasts Club",
        mail: "sportsclub@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"The Amateur Sports Enthusiasts’ Club aims to provide a platform and opportunity for every person on the campus to play and enjoy a sport they love. One of its main goals is to increase female participation by hosting events and tournaments just for them."}]},{"type":"paragraph","children":[{"text":"We hope to not only help the people who play sports, but also watch sports by holding regular match streams and events testing their knowledge and passion for the sport."}]}]',
        instagram: "https://instagram.com/asec_iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/aseciiith?tn-str=k*F",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/CNrbp9znGT",
        __typename: "ClubType",
    },
    {
        id: "25",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/apex.jpg",
        name: "Apex Council",
        mail: "apex@students.iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "2",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/astronom6y.png",
        name: "Astronomy Club",
        mail: "astronomyclub@students.iiit.ac.in",
        website: "",
        category: "TECHNICAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"This is a group of astronomy enthusiasts trying to enjoy our passion and spread it to others."}]}]',
        instagram: "https://instagram.com/astronomy_club_iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/astronomyclub.iiith",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "29",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/campuslife.jpg",
        name: "Campus Life Council",
        mail: "campuslife@students.iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "26",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/cult.JPG",
        name: "Cultural Council",
        mail: "cultural@students.iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "23",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/Cyclorama_The_Film_and_Dramatics_Society_edit_XoeVpUm.png",
        name: "Cyclorama",
        mail: "film.club@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"Theatre and film are an important part of contemporary society and artistic expression. While most of us have access to theatre in the form of popular cinemas, opportunities to explore and appreciate the nuances of cinema and drama remain largely limited."}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "10",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/Decore.png",
        name: "Decore – The Design Club",
        mail: "decore@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "Design from the core",
        description:
            '[{"type":"paragraph","children":[{"text":"With many other clubs having their own design team, the existence of Decore might come across as gratuitous, but that\'s a rather limited view of what we\'re trying to do here. Rather than being just another art club, we’re trying to expand our reach far beyond just that and produce an environment to encompass as much as we can in any sort of visual commentary."}]},{"type":"paragraph","children":[{"text":"Decore is a club specially built for the exploration of ideas and any sort of creativity might just be what one needs for zoning out of the monotony of college routine and letting your thoughts flow."}]}]',
        instagram: "https://instagram.com/decore_iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/decoreiiith",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/Rs6bKF7",
        __typename: "ClubType",
    },
    {
        id: "3",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/dsc.png",
        name: "Developer Student Club",
        mail: "dsc@students.iiit.ac.in",
        website: "",
        category: "TECHNICAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"DSC IIIT Hyderabad is a non-profit developer group powered by Google Developers to learn, share, connect and develop skills. By joining the GDSC, students grow their knowledge in a peer-to-peer learning environment and build solutions for local businesses and their communities."}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "4",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/ERC.png",
        name: "Electronics and Robotics Club",
        mail: "roboticsclub@students.iiit.ac.in",
        website: "",
        category: "TECHNICAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"As the Official Electronics and Robotics club of IIITH, we organize training sessions, lectures, competitions and are associated with building intelligent machines to tackle real-world problems."}]},{"type":"paragraph","children":[{"text":"In essence, we are a diverse bunch of electronics and robotics enthusiasts at IIIT-Hyderabad who strongly believe in being innovative and creating things from the ground up."}]}]',
        instagram: "https://www.instagram.com/erc.iiith/",
        facebook: "https://www.facebook.com/groups/163048550550986",
        youtube: "",
        twitter: "",
        linkedin: "https://www.linkedin.com/company/erc-iiith/",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "31",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/ecell.jpg",
        name: "Entrepreneurship Cell",
        mail: "ecell@iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "32",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/felicity.png",
        name: "Felicity Taskforce",
        mail: "felicity@iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "28",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/fc.jpg",
        name: "Finance Council",
        mail: "finance_council@students.iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "11",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/fhc.jpg",
        name: "Frivolous Humour Club",
        mail: "fhc@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"Frivolous Humor Club, we a bunch of funny people who do funny stuff."}]}]',
        instagram: "https://instagram.com/fhc_iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/groups/2119013058122224",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "8",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/ISAQC.png",
        name: "ISAQC",
        mail: "isaqc@students.iiit.ac.in",
        website: "",
        category: "TECHNICAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"Quantum computing and quantum information technology are expected to provide a distinctive edge in computing power which far outclasses any technology of our time with its potential applications ranging from cryptography and security to drug design and generative chemistry."}]},{"type":"paragraph","children":[{"text":"We are a research club with a focus on systematically building a solid foundation for all members of ISAQC through lectures, seminars and quantum programming workshops along with giving you a working knowledge of quantum algorithms and their applications with the hope that you might be able to design an algorithm of your own someday!"}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/vbYNST5vT4",
        __typename: "ClubType",
    },
    {
        id: "12",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/LitClub_logo.jpg",
        name: "Literary Club",
        mail: "litclub@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"The Literary Club, contrary to what the name might suggest, is not just a conventional group of people who love literature.In addition to being a club that appreciates literature, LitClub is a group of varied interests- from anime to classic literature, from pop culture to poetic romanticism and from visual arts to theatre, we have it all. We, at LitClub greatly believe in using literature as a tool to explore all expressions of art and critique them."}]}]',
        instagram: "https://www.instagram.com/litclub.iiith/",
        facebook: "https://www.facebook.com/litclub.iiith",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/qtqqqjrefc",
        __typename: "ClubType",
    },
    {
        id: "24",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/nss.jpg",
        name: "National Service Scheme",
        mail: "nss@iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "5",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/osdg.png",
        name: "Open-Source Developers Group",
        mail: "osdg@students.iiit.ac.in",
        website: "https://osdg.iiit.ac.in/",
        category: "TECHNICAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"The Open Source Developers Group at IIIT Hyderabad is dedicated to helping student developers improve their skills and contribute to the Open-Source community in a multitude of ways. The group hosts several initiatives like hackathons, workshops and seminars, group discussions(Open Source Saturdays), and community projects to help cultivate the open-source culture in the student community. The institution is also known for actively participating in global Open Source programs like the Google Summer of Code and Outreachy, and we at OSDG wish to encourage more involvement in such areas.","bold":true}]}]',
        instagram: "https://instagram.com/osdg.iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/groups/osdg.iiit.h",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/Nvw9XY3",
        __typename: "ClubType",
    },
    {
        id: "13",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/pentaprism.png",
        name: "Pentaprism",
        mail: "photography@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "The Photography Club of IIITH",
        description:
            '[{"type":"paragraph","children":[{"text":"We believe that photography is a creative medium that is an equal blend of art and science and thus is an ideal creative hobby for us aspiring scientists, engineers and of course, photographers. Let us embark on this creative journey together and help each other learn this somewhat technical art."}]},{"type":"paragraph","children":[{"text":"Pentaprism: The Photography Club is a bunch of photography enthusiasts. We cover events conducted by various other clubs and the institute. We organize our own events such as photo-contests and workshops where enthusiasts learn new photography techniques and showcase their talent."}]}]',
        instagram: "https://instagram.com/photographyclub_iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/photography.iiith",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/EEzJghA",
        __typename: "ClubType",
    },
    {
        id: "33",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/spc.jpg",
        name: "Placement Cell",
        mail: "naren.akash@research.iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "6",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/programming_club.jpg",
        name: "Programming Club",
        mail: "programming.club@students.iiit.ac.in",
        website: "",
        category: "TECHNICAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"The “coding culture” of our college is very well-known amongst the students in India. It’s one of the “cool things” that sets our college apart from other IITs or NITs in India and plays a role in their choosing of our college. Unlike what might be believed, this culture stems from the interest shown by students themselves and is not a result of the course curriculum.At the Programming Club, we strive to maintain IIIT-H’s reputed coding culture, by organizing various events for all levels of participation throughout the year and guiding aspiring students to further excel their skills."}]}]',
        instagram: "",
        facebook: "https://www.facebook.com/groups/267448629933046",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/gkqY2C5XPz ",
        __typename: "ClubType",
    },
    {
        id: "14",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/skate.jpg",
        name: "Skateboarding Club",
        mail: "skateboardingclub@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"The skateboarding club of IIITH exists for the purpose of introducing IIITH students to skateboarding. It became an official IIITH club in March and currently it holds regular sessions every week to teach skateboarding to the students of IIITH."}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "34",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/sports.png",
        name: "Sports Council",
        mail: "sports_secretary@students.iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "27",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/parliament.png",
        name: "Student Parliament",
        mail: "parliament@students.iiit.ac.in",
        website: "",
        category: "OTHER",
        tagline: "",
        description: '[{"type":"paragraph","children":[{"text":""}]}]',
        instagram: "",
        facebook: "",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "",
        __typename: "ClubType",
    },
    {
        id: "15",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/artsoc.jpg",
        name: "The Art Society",
        mail: "artsociety@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"The Art Society is a place for students to practice and hone in on their skills, develop their techniquesand portfolios, collaborate with other artists like themselves, create bonds with the community throughthe arts, and learn how to work together through group projects that will beautify the college andcommunity."}]}]',
        instagram: "https://instagram.com/artsocietyiiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/artsocietyiiit/",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/zjBx6jj9Bb",
        __typename: "ClubType",
    },
    {
        id: "16",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/chess.jpg",
        name: "The Chess Club",
        mail: "chessclub@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"We are a group of chess enthusiasts who aim to popularize this sport. We are a club where participants can learn chess and improve their skills by playing the game. We wish to nurture critical thought, higher-order thinking skills and execution of complex ideas among fellow students via chess training, practice,and tournaments."}]}]',
        instagram: "",
        facebook: "https://www.facebook.com/groups/179860508862382",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/jhYyRpJ",
        __typename: "ClubType",
    },
    {
        id: "17",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/DanceCrew.png",
        name: "The Dance Crew",
        mail: "thedancecrew@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"To give all the people passionate about dance at IIITH a space to showcase and nurture their talents and interests where each style is encouraged, our only criteria being – enthusiasm! It is open to beginners, amateurs, and professionals."}]}]',
        instagram: "https://instagram.com/thedancecrew_iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/dancecrewIIIT",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.com/invite/pfJPGqmJNK",
        __typename: "ClubType",
    },
    {
        id: "18",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/debsoc.png",
        name: "The Debate Society",
        mail: "debsoc@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "The debate society of IIIT-H",
        description:
            '[{"type":"paragraph","children":[{"text":"The Debate Society, IIIT Hyderabad is a student-led club that organises intellectual events, debate tournaments, regular open-to-all practice debates, and MUNs for the IIIT-H community. It also sends a IIIT-H contingent to many national and international debate competitions. It holds regular sessions to educate the IIIT-H community about debating. The two main flagship events held by the Debate Society every semester are a Debate tournament and an MUN conference amongst many more!"}]}]',
        instagram: "https://instagram.com/debsociiit?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/groups/iiithdebsoc",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: " https://discord.gg/NkR2HVDTc8",
        __typename: "ClubType",
    },
    {
        id: "19",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/IMG-20220812-WA0036.jpg",
        name: "The Gaming Club",
        mail: "thegamingclub@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"We as the Gaming Club wish to expand and promote the gaming culture present in IIITH. Supporting both competitive gaming, party gaming and game development to produce and environment where anyone can fit in is the final vision for our club. As far as goals go we are currently in the process of setting upa gaming room for our college."}]}]',
        instagram: "https://instagram.com/tgc_iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/groups/571653139992051/?ref=share",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/fy5GpMf",
        __typename: "ClubType",
    },
    {
        id: "20",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/languageClub.jpeg",
        name: "The Language Club",
        mail: "thelanguageclub@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"The Language Club was created with the intent of providing a supporting group for people at IIIT Hyd looking to learn a new language. Since then, it has also conducted events highlighting different cultures with the objective of raising interest in them and their languages."}]}]',
        instagram: "https://instagram.com/the_language_club_iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/groups/274487826950937/?ref=share",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/Xq3HGw7s7e",
        __typename: "ClubType",
    },
    {
        id: "21",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/music_club.png",
        name: "The Music Club",
        mail: "themusicclub@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "Because without music, life would B flat.",
        description:
            '[{"type":"paragraph","children":[{"text":"The Music Club has been a very active club at IIIT, Hyderabad. We have grown so much over the past few years, coming up with new and creative ideas and organizing various events. We do our level best to keep the Club as active as possible no matter the workload. We do get lots of assignments and have many exams throughout each semester. We may not be able to hold events every week like in other colleges, but we manage to do atleast two major events every semester.We want to keep this going, andkeep upping the game. To sum it all up,to keep the music culture in our college alive is our ultimate objective."}]}]',
        instagram: "https://instagram.com/the_music_club.iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/groups/462111737332193/about",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/c2zEHDr",
        __typename: "ClubType",
    },
    {
        id: "7",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/trg.jpg",
        name: "Theory Group",
        mail: "theory.group@students.iiit.ac.in",
        website: "",
        category: "TECHNICAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"The Theory Group isa place for students of IIIT Hyderabad interested in finding out more and learning about any subject, to come together andidentify common interests."}]}]',
        instagram: "https://instagram.com/theory.group.iiit?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/groups/210017129738577",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/XtHTs678rU",
        __typename: "ClubType",
    },
    {
        id: "22",
        state: "ACTIVE",
        img: "http://clubs.iiit.ac.in/media/imgs/clubs/TVRQC_logo.png",
        name: "The TV Room Quiz Club",
        mail: "quizzing@students.iiit.ac.in",
        website: "",
        category: "CULTURAL",
        tagline: "",
        description:
            '[{"type":"paragraph","children":[{"text":"We are currently a team of 20-25 people, organising quizzes on various topics in IIIT Hyderabad and some which are open to all college students. On an average, we conduct one quiz every 2 months and a huge flagship event for Felicity annually. The monthly quizzes are either made by quiz club alumni, team members or other interested students. We also frequently collaborate with other clubs like ASEC, Lit Club etc. to quiz on more diverse and IIIT Clubs specific themes."}]}]',
        instagram: "https://instagram.com/tvrqc_iiith?igshid=ODBkMDk1MTU=",
        facebook: "https://www.facebook.com/tvrqc/",
        youtube: "",
        twitter: "",
        linkedin: "",
        discord: "https://discord.gg/DMb5FFJ",
        __typename: "ClubType",
    },
];

export default clubs;
