const clubs = [
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "0x1337: The Hacking Club",
        mail: "hacking.club@students.iiit.ac.in",
        category: "technical",
        tagline: "Exploiting vulnerabilities for fun and profit",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Astronomy Club",
        mail: "astronomyclub@students.iiit.ac.in",
        category: "technical",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Developer Student Club",
        mail: "dsc@students.iiit.ac.in",
        category: "technical",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Electronics and Robotics Club",
        mail: "roboticsclub@students.iiit.ac.in",
        category: "technical",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Open-Source Developers Group",
        mail: "osdg@students.iiit.ac.in",
        category: "technical",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Programming Club",
        mail: "programming.club@students.iiit.ac.in",
        category: "technical",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Theory Group",
        mail: "theory.group@students.iiit.ac.in",
        category: "technical",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "ISAQC",
        mail: "isaqc@students.iiit.ac.in",
        category: "technical",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Amateur Sports Enthusiasts Club",
        mail: "sportsclub@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Decore – The Design Club",
        mail: "decore@students.iiit.ac.in",
        category: "cultural",
        tagline: "Design from the core",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Frivolous Humour Club",
        mail: "fhc@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Literary Club",
        mail: "litclub@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Pentaprism",
        mail: "photography@students.iiit.ac.in",
        category: "cultural",
        tagline: "The Photography Club of IIITH",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Skateboarding Club",
        mail: "skateboardingclub@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "The Art Society",
        mail: "artsociety@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "The Chess Club",
        mail: "chessclub@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "The Dance Crew",
        mail: "thedancecrew@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "The Debate Society",
        mail: "debsoc@students.iiit.ac.in",
        category: "cultural",
        tagline: "The debate society of IIIT-H",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "The Gaming Club",
        mail: "thegamingclub@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "The Language Club",
        mail: "thelanguageclub@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "The Music Club",
        mail: "themusicclub@students.iiit.ac.in",
        category: "cultural",
        tagline: "Because without music, life would B flat.",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "The TV Room Quiz Club",
        mail: "quizzing@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Cyclorama",
        mail: "film.club@students.iiit.ac.in",
        category: "cultural",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "National Service Scheme",
        mail: "nss@iiit.ac.in",
        category: "other",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Apex Council",
        mail: "apex@students.iiit.ac.in",
        category: "other",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Cultural Council",
        mail: "cultural@students.iiit.ac.in",
        category: "other",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Student Parliament",
        mail: "parliament@students.iiit.ac.in",
        category: "other",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Finance Council",
        mail: "finance_council@students.iiit.ac.in",
        category: "other",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Campus Life Council",
        mail: "campuslife@students.iiit.ac.in",
        category: "other",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Alumni Cell",
        mail: "alumnicell@iiit.ac.in",
        category: "other",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Entrepreneurship Cell",
        mail: "ecell@iiit.ac.in",
        category: "other",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Felicity Taskforce",
        mail: "felicity@iiit.ac.in",
        category: "other",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Placement Cell",
        mail: "naren.akash@research.iiit.ac.in",
        category: "other",
        tagline: "",
    },
    {
        id: 0,
        img: "https://clubs.iiit.ac.in/media/imgs/clubs/club_placeholder.jpg",
        name: "Sports Council",
        mail: "sports_secretary@students.iiit.ac.in",
        category: "other",
        tagline: "",
    },
];

export default clubs;
