const events = [
    {
        id: "3",
        club: {
            id: "19",
            name: "The Gaming Club",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/IMG-20220812-WA0036.jpg",
            __typename: "ClubType",
        },
        datetimeStart: "2022-10-12T15:00:00+00:00",
        datetimeEnd: "2022-10-12T18:00:00+00:00",
        poster: "",
        name: "Geoguesser",
        audience: "ug1,ug2,ug3,ugx,pg",
        description: "No description available.",
        state: "A_4",
        __typename: "EventType",
    },
    {
        id: "2",
        club: {
            id: "21",
            name: "The Music Club",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/music_club.png",
            __typename: "ClubType",
        },
        datetimeStart: "2022-10-20T18:00:00+00:00",
        datetimeEnd: "2022-10-20T22:00:00+00:00",
        poster: "",
        name: "Unplugged",
        audience: "ug1,ug2,ug3,ugx,pg,faculty",
        description: "No description available.",
        state: "A_4",
        __typename: "EventType",
    },
    {
        id: "4",
        club: {
            id: "31",
            name: "Entrepreneurship Cell",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/ecell.jpg",
            __typename: "ClubType",
        },
        datetimeStart: "2022-10-22T15:30:00+00:00",
        datetimeEnd: "2022-10-23T20:30:00+00:00",
        poster: "",
        name: "Megathon",
        audience: "ug1,ug2,ug3,ugx,pg",
        description: "No description available.",
        state: "A_4",
        __typename: "EventType",
    },
    {
        id: "1",
        club: {
            id: "5",
            name: "Open-Source Developers Group",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/osdg.png",
            __typename: "ClubType",
        },
        datetimeStart: "2022-10-27T15:30:00+00:00",
        datetimeEnd: "2022-10-27T17:30:00+00:00",
        poster: "",
        name: "Talk by Richard Stallman",
        audience: "ug1,ug2,ug3,ugx,pg,staff,faculty",
        description: "No description available.",
        state: "A_4",
        __typename: "EventType",
    },
    {
        id: "5",
        club: {
            id: "25",
            name: "Apex Council",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/apex.jpg",
            __typename: "ClubType",
        },
        datetimeStart: "2022-10-30T03:30:00+00:00",
        datetimeEnd: "2022-10-30T07:00:00+00:00",
        poster: "http://clubs.iiit.ac.in/media/imgs/events/Intro.jpg",
        name: "Intro to Student Bodies 1",
        audience: "ug1",
        description: "No description available.",
        state: "A_4",
        __typename: "EventType",
    },
    {
        id: "6",
        club: {
            id: "5",
            name: "Open-Source Developers Group",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/osdg.png",
            __typename: "ClubType",
        },
        datetimeStart: "2022-10-30T08:30:00+00:00",
        datetimeEnd: "2022-10-30T10:30:00+00:00",
        poster: "http://clubs.iiit.ac.in/media/imgs/events/linux.jpg",
        name: "Linux Fest",
        audience: "ug1,ug2",
        description: "No description available.",
        state: "A_4",
        __typename: "EventType",
    },
    {
        id: "9",
        club: {
            id: "12",
            name: "Literary Club",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/LitClub_logo.jpg",
            __typename: "ClubType",
        },
        datetimeStart: "2022-10-30T10:30:00+00:00",
        datetimeEnd: "2022-10-30T14:30:00+00:00",
        poster: "http://clubs.iiit.ac.in/media/imgs/events/treasurehunt.jpg",
        name: "Treasure Hunt",
        audience: "ug1",
        description: "No description available.",
        state: "A_4",
        __typename: "EventType",
    },
    {
        id: "7",
        club: {
            id: "25",
            name: "Apex Council",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/apex.jpg",
            __typename: "ClubType",
        },
        datetimeStart: "2022-10-31T12:00:00+00:00",
        datetimeEnd: "2022-10-31T14:00:00+00:00",
        poster: "http://clubs.iiit.ac.in/media/imgs/events/Intro2.jpg",
        name: "Intro to Student Bodies 2",
        audience: "ug1",
        description: "No description available.",
        state: "A_4",
        __typename: "EventType",
    },
    {
        id: "10",
        club: {
            id: "13",
            name: "Pentaprism",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/pentaprism.png",
            __typename: "ClubType",
        },
        datetimeStart: "2022-11-02T10:00:00+00:00",
        datetimeEnd: "2022-11-02T12:00:00+00:00",
        poster: "http://clubs.iiit.ac.in/media/imgs/events/photography.jpg",
        name: "Clash of Clusters Photo Contest",
        audience: "ug1",
        description: "No description available.",
        state: "A_3",
        __typename: "EventType",
    },
    {
        id: "11",
        club: {
            id: "4",
            name: "Electronics and Robotics Club",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/ERC.png",
            __typename: "ClubType",
        },
        datetimeStart: "2022-11-02T12:00:00+00:00",
        datetimeEnd: "2022-11-02T14:00:00+00:00",
        poster: "http://clubs.iiit.ac.in/media/imgs/events/Arduino.jpg",
        name: "Intro to Arduino",
        audience: "ug1",
        description: "No description available.",
        state: "A_3",
        __typename: "EventType",
    },
    {
        id: "8",
        club: {
            id: "5",
            name: "Open-Source Developers Group",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/osdg.png",
            __typename: "ClubType",
        },
        datetimeStart: "2022-11-02T15:00:00+00:00",
        datetimeEnd: "2022-11-02T17:30:00+00:00",
        poster: "http://clubs.iiit.ac.in/media/imgs/events/linux.jpg",
        name: "Linux Fest Doubt Session",
        audience: "ug1,ug2",
        description: "No description available.",
        state: "A_3",
        __typename: "EventType",
    },
    {
        id: "12",
        club: {
            id: "17",
            name: "The Dance Crew",
            img: "http://clubs.iiit.ac.in/media/imgs/clubs/DanceCrew.png",
            __typename: "ClubType",
        },
        datetimeStart: "2022-11-03T12:00:00+00:00",
        datetimeEnd: "2022-11-03T15:00:00+00:00",
        poster: "http://clubs.iiit.ac.in/media/imgs/events/dance_music.jpg",
        name: "Just Dance",
        audience: "ug1",
        description: "No description available.",
        state: "A_3",
        __typename: "EventType",
    },
];

export default events;
