const members = [
    {
        id: "1089",
        user: {
            id: "820",
            img: "http://clubs.iiit.ac.in/media/imgs/users/2021112013.jpg",
            firstName: "Aadarsh",
            lastName: "Devanand",
            mail: "aadarsh.devanand@research.iiit.ac.in",
            rollno: 2021112013,
            batch: "UG2K21",
            __typename: "UserType",
        },
        role: "Organizing Team",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1090",
        user: {
            id: "821",
            img: "",
            firstName: "Amogha",
            lastName: "A Halhalli",
            mail: "amogha.halhalli@students.iiit.ac.in",
            rollno: 2021101007,
            batch: "UG2K21",
            __typename: "UserType",
        },
        role: "Organizing Team",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1091",
        user: {
            id: "822",
            img: "http://clubs.iiit.ac.in/media/imgs/users/2020113017.jpg",
            firstName: "Dhruv",
            lastName: "Mittal",
            mail: "dhruv.m@research.iiit.ac.in",
            rollno: 2020113017,
            batch: "UG2K20",
            __typename: "UserType",
        },
        role: "Coordinator",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1092",
        user: {
            id: "823",
            img: "http://clubs.iiit.ac.in/media/imgs/users/2021114016.jpg",
            firstName: "Hardik",
            lastName: "Mittal",
            mail: "hardik.mittal@research.iiit.ac.in",
            rollno: 2021114016,
            batch: "UG2K21",
            __typename: "UserType",
        },
        role: "Coordinator",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1093",
        user: {
            id: "824",
            img: "http://clubs.iiit.ac.in/media/imgs/users/2021101065.jpg",
            firstName: "Kommireddy",
            lastName: "Bhargav Srinivas",
            mail: "Bhargav.srinivas@students.iiit.ac.in ",
            rollno: 2021101065,
            batch: "UG2K21",
            __typename: "UserType",
        },
        role: "Organizing Team",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1094",
        user: {
            id: "825",
            img: "http://clubs.iiit.ac.in/media/imgs/users/2020113005.jpg",
            firstName: "Mihir",
            lastName: "Rawat",
            mail: "mihir.r@research.iiit.ac.in",
            rollno: 2020113005,
            batch: "UG2K20",
            __typename: "UserType",
        },
        role: "Coordinator",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1095",
        user: {
            id: "826",
            img: "http://clubs.iiit.ac.in/media/imgs/users/2021111021.jpg",
            firstName: "Muhammed",
            lastName: "Shamil K",
            mail: "muhammed.shamil@research.iiit.ac.in",
            rollno: 2021111021,
            batch: "UG2K21",
            __typename: "UserType",
        },
        role: "Coordinator",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1096",
        user: {
            id: "827",
            img: "",
            firstName: "Naimeesh",
            lastName: "Narayan Tiwari",
            mail: "naimeesh.tiwari@students.iiit.ac.in",
            rollno: 2020101074,
            batch: "UG2K20",
            __typename: "UserType",
        },
        role: "Organizing Team",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1097",
        user: {
            id: "9",
            img: "http://clubs.iiit.ac.in/media/imgs/users/2020101108.jpg",
            firstName: "Pranjal",
            lastName: "Thapliyal",
            mail: "pranjal.thapliyal@students.iiit.ac.in",
            rollno: 2020101108,
            batch: "UG2K20",
            __typename: "UserType",
        },
        role: "Organizing Team",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1098",
        user: {
            id: "828",
            img: "",
            firstName: "Rahul",
            lastName: "Garg",
            mail: "rahul.garg@research.iiit.ac.in",
            rollno: 2020115006,
            batch: "UG2K20",
            __typename: "UserType",
        },
        role: "Organizing Team",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1099",
        user: {
            id: "829",
            img: "",
            firstName: "Sarthak",
            lastName: "Bansal",
            mail: "sarthak.bansal@students.iiit.ac.in",
            rollno: 2021101134,
            batch: "UG2K21",
            __typename: "UserType",
        },
        role: "Organizing Team",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1100",
        user: {
            id: "830",
            img: "",
            firstName: "Srijan",
            lastName: "Chakraborty",
            mail: "srijan.chakraborty@research.iiit.ac.in",
            rollno: 2020115001,
            batch: "UG2K20",
            __typename: "UserType",
        },
        role: "Organizing Team",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1101",
        user: {
            id: "831",
            img: "",
            firstName: "Vedant",
            lastName: "Parekh",
            mail: "vedant.p@research.iiit.ac.in",
            rollno: 2020113016,
            batch: "UG2K20",
            __typename: "UserType",
        },
        role: "Organizing Team",
        year: 2022,
        approved: true,
        __typename: "MemberType",
    },
    {
        id: "1102",
        user: {
            id: "833",
            img: "",
            firstName: "Vishva",
            lastName: "R",
            mail: "vishva.saravanan@research.iiit.ac.in",
            rollno: 2019113019,
            batch: "UG2K19",
            __typename: "UserType",
        },
        role: "Coordinator",
        year: 2021,
        approved: true,
        __typename: "MemberType",
    },
];

export default members;
